#!/bin/bash

DIR="$(dirname $0)/$(dirname "$(readlink "$0")")"
FALLBACK_FILE="${HOME}/.uyamlspec.txt"

if [ -e ${FALLBACK_FILE} ]; then
    ${DIR}/../libexec/UnityYAMLMerge merge -h "$@" --fallback "${FALLBACK_FILE}"
else
    ${DIR}/../libexec/UnityYAMLMerge merge -h "$@"
fi
