#!/bin/bash

DIR="$(dirname $0)/$(dirname "$(readlink "$0")")"/../libexec

FALLBACK_FILE="${HOME}/.uyamlspec.txt"

if [ -e ${FALLBACK_FILE} ]; then
	${DIR}/UnityYAMLMerge merge -h --fallback "${FALLBACK_FILE}" "$@"
else
	${DIR}/UnityYAMLMerge merge -h "$@"
fi
